### ISSUE TITLE
Are Heel toe and happy feet the same step? 

### ISSUE THREAD

**Issue by filhodanuvem** [gpechim/learn-hiphop#1]
I saw [here](https://www.youtube.com/watch?v=A-9RWQc4tzE) that heel toe and happy feet are the same steps, but I also remember/found the follow links 

[Heel Toe](https://www.youtube.com/watch?v=rOV-g2jMHxs) 

[Happy feet](https://www.youtube.com/watch?v=Rig-YmEveDY)

What do you think ?

**Comment by gpechim** [comment]
Nice Claw! 
That's right, both are one step. (I did it just to see if you was watching ... haha)

**Comment by cloudson** [comment]
hahahhaha. But its better show the different links on readme/web page right ? I will do another pr soon about it.
